/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QCustomPlot *plottsgram;
    QTabWidget *tw;
    QWidget *tab;
    QPushButton *btnGetFallDuration;
    QLineEdit *leFallDuration;
    QPushButton *btnGetHeightInst;
    QLineEdit *leHeightInstallation;
    QPushButton *btnGetAngleInst;
    QLineEdit *leAngleXInstallation;
    QLineEdit *leAngleYInstallation;
    QLineEdit *leAngleZInstallation;
    QPushButton *btnCmdInitCompleteCek;
    QLineEdit *leInitComplete;
    QPushButton *btnGetFirmwareVersion;
    QLineEdit *leFirmwareVersion;
    QPushButton *btnHWModel;
    QLineEdit *leHWModel;
    QPushButton *btnGetProductModel;
    QLineEdit *leProductModel;
    QPushButton *btnGetProductID;
    QLineEdit *leProductID;
    QWidget *tab_5;
    QLineEdit *leFirmwareVersion2;
    QPushButton *btnGetProductModel2;
    QLineEdit *leInitComplete2;
    QLineEdit *leAngleZInstallation2;
    QLineEdit *leAngleYInstallation2;
    QLineEdit *leHWModel2;
    QLineEdit *leProductModel2;
    QLineEdit *leHeightInstallation2;
    QPushButton *btnCmdInitCompleteCek2;
    QPushButton *btnGetProductID2;
    QLineEdit *leFallDuration2;
    QLineEdit *leProductID2;
    QPushButton *btnGetFallDuration2;
    QLineEdit *leAngleXInstallation2;
    QPushButton *btnHWModel2;
    QPushButton *btnGetAngleInst2;
    QPushButton *btnGetFirmwareVersion2;
    QPushButton *btnGetHeightInst2;
    QWidget *tab_2;
    QFrame *frame;
    QCheckBox *cbPresence;
    QLineEdit *lePresence;
    QFrame *frameFallDetection;
    QCheckBox *cbFallDetection;
    QFrame *frameFallDetection_2;
    QLineEdit *leFallDetection;
    QFrame *frame_2;
    QCheckBox *cbStandStill;
    QFrame *frame_3;
    QCheckBox *cbStandStill_2;
    QLineEdit *leGetStandStill;
    QPushButton *btnSetHeight;
    QLineEdit *leSetHeight;
    QLineEdit *leSetFallDuration;
    QPushButton *btnSetFallDuration;
    QPushButton *btnSetAngle;
    QLineEdit *leAngleX;
    QLineEdit *leAngleY;
    QLineEdit *leAngleZ;
    QFrame *frame_4;
    QCheckBox *cbTraceTracking;
    QLineEdit *leTraceTracking;
    QComboBox *serialPortInfoListBox;
    QPushButton *btnOpenSerialPort;
    QPushButton *btnLoad;
    QWidget *tab_4;
    QLineEdit *lePresence2;
    QFrame *frame_9;
    QCheckBox *cbTraceTracking2;
    QPushButton *btnSetHeight2;
    QLineEdit *leAngleX2;
    QComboBox *serialPortInfoListBox2;
    QLineEdit *leAngleY2;
    QPushButton *btnLoad2;
    QLineEdit *leSetHeight2;
    QLineEdit *leFallDetection2;
    QPushButton *btnSetFallDuration2;
    QLineEdit *leTraceTracking2;
    QPushButton *btnOpenSerialPort2;
    QFrame *frame_10;
    QCheckBox *cbPresence2;
    QLineEdit *leGetStandStill2;
    QPushButton *btnSetAngle2;
    QFrame *frameFallDetection_5;
    QCheckBox *cbFallDetection2;
    QFrame *frameFallDetection_6;
    QFrame *frame_11;
    QCheckBox *cbStandStill2;
    QFrame *frame_12;
    QCheckBox *cbStandStill_6;
    QLineEdit *leSetFallDuration2;
    QLineEdit *leAngleZ2;
    QWidget *tab_3;
    QLabel *label_3;
    QLineEdit *leMotion;
    QLabel *label_2;
    QLineEdit *leStandStill;
    QLabel *label;
    QPushButton *btnTestFall;
    QLabel *leFallState;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *leFallPosX;
    QLineEdit *leFallPosY;
    QLabel *label_7;
    QLineEdit *leVelocity;
    QLabel *label_6;
    QLineEdit *leTraceNumber;
    QCheckBox *cbSocket;
    QPlainTextEdit *logEdit;
    QWidget *tab_6;
    QLabel *label_15;
    QLabel *label_16;
    QPushButton *btnTestFall2;
    QLineEdit *leTraceNumber2;
    QPlainTextEdit *logEdit2;
    QLineEdit *leFallPosY2;
    QLabel *label_17;
    QLineEdit *leVelocity2;
    QLabel *leFallState2;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *leStandStill2;
    QLineEdit *leFallPosX2;
    QLineEdit *leMotion2;
    QCheckBox *cbSocket2;
    QLabel *label_21;
    QCustomPlot *plotRadar;
    QCustomPlot *plottsVelocity;
    QCustomPlot *plottsgram2;
    QCustomPlot *plottsVelocity2;
    QCustomPlot *plotRadar2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(889, 545);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName("centralWidget");
        plottsgram = new QCustomPlot(centralWidget);
        plottsgram->setObjectName("plottsgram");
        plottsgram->setGeometry(QRect(370, 10, 250, 150));
        QSizePolicy sizePolicy(QSizePolicy::Policy::Preferred, QSizePolicy::Policy::MinimumExpanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(plottsgram->sizePolicy().hasHeightForWidth());
        plottsgram->setSizePolicy(sizePolicy);
        tw = new QTabWidget(centralWidget);
        tw->setObjectName("tw");
        tw->setGeometry(QRect(10, 10, 361, 441));
        tab = new QWidget();
        tab->setObjectName("tab");
        btnGetFallDuration = new QPushButton(tab);
        btnGetFallDuration->setObjectName("btnGetFallDuration");
        btnGetFallDuration->setGeometry(QRect(10, 360, 101, 51));
        leFallDuration = new QLineEdit(tab);
        leFallDuration->setObjectName("leFallDuration");
        leFallDuration->setGeometry(QRect(120, 370, 141, 31));
        btnGetHeightInst = new QPushButton(tab);
        btnGetHeightInst->setObjectName("btnGetHeightInst");
        btnGetHeightInst->setGeometry(QRect(10, 310, 101, 51));
        leHeightInstallation = new QLineEdit(tab);
        leHeightInstallation->setObjectName("leHeightInstallation");
        leHeightInstallation->setGeometry(QRect(120, 320, 141, 31));
        btnGetAngleInst = new QPushButton(tab);
        btnGetAngleInst->setObjectName("btnGetAngleInst");
        btnGetAngleInst->setGeometry(QRect(10, 260, 101, 51));
        leAngleXInstallation = new QLineEdit(tab);
        leAngleXInstallation->setObjectName("leAngleXInstallation");
        leAngleXInstallation->setGeometry(QRect(120, 270, 41, 31));
        leAngleYInstallation = new QLineEdit(tab);
        leAngleYInstallation->setObjectName("leAngleYInstallation");
        leAngleYInstallation->setGeometry(QRect(170, 270, 41, 31));
        leAngleZInstallation = new QLineEdit(tab);
        leAngleZInstallation->setObjectName("leAngleZInstallation");
        leAngleZInstallation->setGeometry(QRect(220, 270, 41, 31));
        btnCmdInitCompleteCek = new QPushButton(tab);
        btnCmdInitCompleteCek->setObjectName("btnCmdInitCompleteCek");
        btnCmdInitCompleteCek->setGeometry(QRect(10, 210, 101, 51));
        leInitComplete = new QLineEdit(tab);
        leInitComplete->setObjectName("leInitComplete");
        leInitComplete->setGeometry(QRect(120, 220, 141, 31));
        btnGetFirmwareVersion = new QPushButton(tab);
        btnGetFirmwareVersion->setObjectName("btnGetFirmwareVersion");
        btnGetFirmwareVersion->setGeometry(QRect(10, 160, 101, 51));
        leFirmwareVersion = new QLineEdit(tab);
        leFirmwareVersion->setObjectName("leFirmwareVersion");
        leFirmwareVersion->setGeometry(QRect(120, 170, 141, 31));
        btnHWModel = new QPushButton(tab);
        btnHWModel->setObjectName("btnHWModel");
        btnHWModel->setGeometry(QRect(10, 110, 101, 51));
        leHWModel = new QLineEdit(tab);
        leHWModel->setObjectName("leHWModel");
        leHWModel->setGeometry(QRect(120, 120, 141, 31));
        btnGetProductModel = new QPushButton(tab);
        btnGetProductModel->setObjectName("btnGetProductModel");
        btnGetProductModel->setGeometry(QRect(10, 60, 101, 51));
        leProductModel = new QLineEdit(tab);
        leProductModel->setObjectName("leProductModel");
        leProductModel->setGeometry(QRect(120, 70, 141, 31));
        btnGetProductID = new QPushButton(tab);
        btnGetProductID->setObjectName("btnGetProductID");
        btnGetProductID->setGeometry(QRect(10, 10, 101, 51));
        leProductID = new QLineEdit(tab);
        leProductID->setObjectName("leProductID");
        leProductID->setGeometry(QRect(120, 20, 141, 31));
        tw->addTab(tab, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName("tab_5");
        leFirmwareVersion2 = new QLineEdit(tab_5);
        leFirmwareVersion2->setObjectName("leFirmwareVersion2");
        leFirmwareVersion2->setGeometry(QRect(120, 160, 141, 31));
        btnGetProductModel2 = new QPushButton(tab_5);
        btnGetProductModel2->setObjectName("btnGetProductModel2");
        btnGetProductModel2->setGeometry(QRect(10, 50, 101, 51));
        leInitComplete2 = new QLineEdit(tab_5);
        leInitComplete2->setObjectName("leInitComplete2");
        leInitComplete2->setGeometry(QRect(120, 210, 141, 31));
        leAngleZInstallation2 = new QLineEdit(tab_5);
        leAngleZInstallation2->setObjectName("leAngleZInstallation2");
        leAngleZInstallation2->setGeometry(QRect(220, 260, 41, 31));
        leAngleYInstallation2 = new QLineEdit(tab_5);
        leAngleYInstallation2->setObjectName("leAngleYInstallation2");
        leAngleYInstallation2->setGeometry(QRect(170, 260, 41, 31));
        leHWModel2 = new QLineEdit(tab_5);
        leHWModel2->setObjectName("leHWModel2");
        leHWModel2->setGeometry(QRect(120, 110, 141, 31));
        leProductModel2 = new QLineEdit(tab_5);
        leProductModel2->setObjectName("leProductModel2");
        leProductModel2->setGeometry(QRect(120, 60, 141, 31));
        leHeightInstallation2 = new QLineEdit(tab_5);
        leHeightInstallation2->setObjectName("leHeightInstallation2");
        leHeightInstallation2->setGeometry(QRect(120, 310, 141, 31));
        btnCmdInitCompleteCek2 = new QPushButton(tab_5);
        btnCmdInitCompleteCek2->setObjectName("btnCmdInitCompleteCek2");
        btnCmdInitCompleteCek2->setGeometry(QRect(10, 200, 101, 51));
        btnGetProductID2 = new QPushButton(tab_5);
        btnGetProductID2->setObjectName("btnGetProductID2");
        btnGetProductID2->setGeometry(QRect(10, 0, 101, 51));
        leFallDuration2 = new QLineEdit(tab_5);
        leFallDuration2->setObjectName("leFallDuration2");
        leFallDuration2->setGeometry(QRect(120, 360, 141, 31));
        leProductID2 = new QLineEdit(tab_5);
        leProductID2->setObjectName("leProductID2");
        leProductID2->setGeometry(QRect(120, 10, 141, 31));
        btnGetFallDuration2 = new QPushButton(tab_5);
        btnGetFallDuration2->setObjectName("btnGetFallDuration2");
        btnGetFallDuration2->setGeometry(QRect(10, 350, 101, 51));
        leAngleXInstallation2 = new QLineEdit(tab_5);
        leAngleXInstallation2->setObjectName("leAngleXInstallation2");
        leAngleXInstallation2->setGeometry(QRect(120, 260, 41, 31));
        btnHWModel2 = new QPushButton(tab_5);
        btnHWModel2->setObjectName("btnHWModel2");
        btnHWModel2->setGeometry(QRect(10, 100, 101, 51));
        btnGetAngleInst2 = new QPushButton(tab_5);
        btnGetAngleInst2->setObjectName("btnGetAngleInst2");
        btnGetAngleInst2->setGeometry(QRect(10, 250, 101, 51));
        btnGetFirmwareVersion2 = new QPushButton(tab_5);
        btnGetFirmwareVersion2->setObjectName("btnGetFirmwareVersion2");
        btnGetFirmwareVersion2->setGeometry(QRect(10, 150, 101, 51));
        btnGetHeightInst2 = new QPushButton(tab_5);
        btnGetHeightInst2->setObjectName("btnGetHeightInst2");
        btnGetHeightInst2->setGeometry(QRect(10, 300, 101, 51));
        tw->addTab(tab_5, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName("tab_2");
        frame = new QFrame(tab_2);
        frame->setObjectName("frame");
        frame->setGeometry(QRect(20, 10, 120, 41));
        frame->setFrameShape(QFrame::Shape::StyledPanel);
        frame->setFrameShadow(QFrame::Shadow::Raised);
        cbPresence = new QCheckBox(frame);
        cbPresence->setObjectName("cbPresence");
        cbPresence->setGeometry(QRect(10, 10, 86, 20));
        lePresence = new QLineEdit(tab_2);
        lePresence->setObjectName("lePresence");
        lePresence->setGeometry(QRect(150, 10, 101, 41));
        frameFallDetection = new QFrame(tab_2);
        frameFallDetection->setObjectName("frameFallDetection");
        frameFallDetection->setGeometry(QRect(20, 50, 121, 41));
        frameFallDetection->setFrameShape(QFrame::Shape::StyledPanel);
        frameFallDetection->setFrameShadow(QFrame::Shadow::Raised);
        cbFallDetection = new QCheckBox(frameFallDetection);
        cbFallDetection->setObjectName("cbFallDetection");
        cbFallDetection->setGeometry(QRect(10, 10, 111, 20));
        frameFallDetection_2 = new QFrame(frameFallDetection);
        frameFallDetection_2->setObjectName("frameFallDetection_2");
        frameFallDetection_2->setGeometry(QRect(70, 40, 121, 41));
        frameFallDetection_2->setFrameShape(QFrame::Shape::StyledPanel);
        frameFallDetection_2->setFrameShadow(QFrame::Shadow::Raised);
        leFallDetection = new QLineEdit(tab_2);
        leFallDetection->setObjectName("leFallDetection");
        leFallDetection->setGeometry(QRect(150, 50, 101, 41));
        frame_2 = new QFrame(tab_2);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(20, 90, 120, 41));
        frame_2->setFrameShape(QFrame::Shape::StyledPanel);
        frame_2->setFrameShadow(QFrame::Shadow::Raised);
        cbStandStill = new QCheckBox(frame_2);
        cbStandStill->setObjectName("cbStandStill");
        cbStandStill->setGeometry(QRect(10, 10, 101, 20));
        frame_3 = new QFrame(frame_2);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(60, 40, 120, 41));
        frame_3->setFrameShape(QFrame::Shape::StyledPanel);
        frame_3->setFrameShadow(QFrame::Shadow::Raised);
        cbStandStill_2 = new QCheckBox(frame_3);
        cbStandStill_2->setObjectName("cbStandStill_2");
        cbStandStill_2->setGeometry(QRect(10, 10, 101, 20));
        leGetStandStill = new QLineEdit(tab_2);
        leGetStandStill->setObjectName("leGetStandStill");
        leGetStandStill->setGeometry(QRect(150, 90, 101, 41));
        btnSetHeight = new QPushButton(tab_2);
        btnSetHeight->setObjectName("btnSetHeight");
        btnSetHeight->setGeometry(QRect(20, 170, 121, 51));
        leSetHeight = new QLineEdit(tab_2);
        leSetHeight->setObjectName("leSetHeight");
        leSetHeight->setGeometry(QRect(150, 170, 101, 41));
        leSetFallDuration = new QLineEdit(tab_2);
        leSetFallDuration->setObjectName("leSetFallDuration");
        leSetFallDuration->setGeometry(QRect(150, 220, 101, 41));
        btnSetFallDuration = new QPushButton(tab_2);
        btnSetFallDuration->setObjectName("btnSetFallDuration");
        btnSetFallDuration->setGeometry(QRect(20, 220, 121, 51));
        btnSetAngle = new QPushButton(tab_2);
        btnSetAngle->setObjectName("btnSetAngle");
        btnSetAngle->setGeometry(QRect(20, 270, 121, 51));
        leAngleX = new QLineEdit(tab_2);
        leAngleX->setObjectName("leAngleX");
        leAngleX->setGeometry(QRect(150, 270, 31, 41));
        leAngleY = new QLineEdit(tab_2);
        leAngleY->setObjectName("leAngleY");
        leAngleY->setGeometry(QRect(190, 270, 31, 41));
        leAngleZ = new QLineEdit(tab_2);
        leAngleZ->setObjectName("leAngleZ");
        leAngleZ->setGeometry(QRect(230, 270, 31, 41));
        frame_4 = new QFrame(tab_2);
        frame_4->setObjectName("frame_4");
        frame_4->setGeometry(QRect(20, 130, 121, 41));
        frame_4->setFrameShape(QFrame::Shape::StyledPanel);
        frame_4->setFrameShadow(QFrame::Shadow::Raised);
        cbTraceTracking = new QCheckBox(frame_4);
        cbTraceTracking->setObjectName("cbTraceTracking");
        cbTraceTracking->setGeometry(QRect(0, 10, 121, 20));
        leTraceTracking = new QLineEdit(tab_2);
        leTraceTracking->setObjectName("leTraceTracking");
        leTraceTracking->setGeometry(QRect(150, 130, 101, 41));
        serialPortInfoListBox = new QComboBox(tab_2);
        serialPortInfoListBox->setObjectName("serialPortInfoListBox");
        serialPortInfoListBox->setGeometry(QRect(10, 320, 131, 32));
        btnOpenSerialPort = new QPushButton(tab_2);
        btnOpenSerialPort->setObjectName("btnOpenSerialPort");
        btnOpenSerialPort->setEnabled(false);
        btnOpenSerialPort->setGeometry(QRect(20, 350, 121, 41));
        QFont font;
        font.setFamilies({QString::fromUtf8(".AppleSystemUIFont")});
        btnOpenSerialPort->setFont(font);
        btnLoad = new QPushButton(tab_2);
        btnLoad->setObjectName("btnLoad");
        btnLoad->setGeometry(QRect(150, 310, 111, 81));
        tw->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName("tab_4");
        lePresence2 = new QLineEdit(tab_4);
        lePresence2->setObjectName("lePresence2");
        lePresence2->setGeometry(QRect(140, 0, 101, 41));
        frame_9 = new QFrame(tab_4);
        frame_9->setObjectName("frame_9");
        frame_9->setGeometry(QRect(10, 120, 121, 41));
        frame_9->setFrameShape(QFrame::Shape::StyledPanel);
        frame_9->setFrameShadow(QFrame::Shadow::Raised);
        cbTraceTracking2 = new QCheckBox(frame_9);
        cbTraceTracking2->setObjectName("cbTraceTracking2");
        cbTraceTracking2->setGeometry(QRect(0, 10, 121, 20));
        btnSetHeight2 = new QPushButton(tab_4);
        btnSetHeight2->setObjectName("btnSetHeight2");
        btnSetHeight2->setGeometry(QRect(10, 160, 121, 51));
        leAngleX2 = new QLineEdit(tab_4);
        leAngleX2->setObjectName("leAngleX2");
        leAngleX2->setGeometry(QRect(140, 260, 31, 41));
        serialPortInfoListBox2 = new QComboBox(tab_4);
        serialPortInfoListBox2->setObjectName("serialPortInfoListBox2");
        serialPortInfoListBox2->setGeometry(QRect(0, 310, 131, 32));
        leAngleY2 = new QLineEdit(tab_4);
        leAngleY2->setObjectName("leAngleY2");
        leAngleY2->setGeometry(QRect(180, 260, 31, 41));
        btnLoad2 = new QPushButton(tab_4);
        btnLoad2->setObjectName("btnLoad2");
        btnLoad2->setGeometry(QRect(140, 300, 111, 81));
        leSetHeight2 = new QLineEdit(tab_4);
        leSetHeight2->setObjectName("leSetHeight2");
        leSetHeight2->setGeometry(QRect(140, 160, 101, 41));
        leFallDetection2 = new QLineEdit(tab_4);
        leFallDetection2->setObjectName("leFallDetection2");
        leFallDetection2->setGeometry(QRect(140, 40, 101, 41));
        btnSetFallDuration2 = new QPushButton(tab_4);
        btnSetFallDuration2->setObjectName("btnSetFallDuration2");
        btnSetFallDuration2->setGeometry(QRect(10, 210, 121, 51));
        leTraceTracking2 = new QLineEdit(tab_4);
        leTraceTracking2->setObjectName("leTraceTracking2");
        leTraceTracking2->setGeometry(QRect(140, 120, 101, 41));
        btnOpenSerialPort2 = new QPushButton(tab_4);
        btnOpenSerialPort2->setObjectName("btnOpenSerialPort2");
        btnOpenSerialPort2->setEnabled(false);
        btnOpenSerialPort2->setGeometry(QRect(10, 340, 121, 41));
        btnOpenSerialPort2->setFont(font);
        frame_10 = new QFrame(tab_4);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(10, 0, 120, 41));
        frame_10->setFrameShape(QFrame::Shape::StyledPanel);
        frame_10->setFrameShadow(QFrame::Shadow::Raised);
        cbPresence2 = new QCheckBox(frame_10);
        cbPresence2->setObjectName("cbPresence2");
        cbPresence2->setGeometry(QRect(10, 10, 86, 20));
        leGetStandStill2 = new QLineEdit(tab_4);
        leGetStandStill2->setObjectName("leGetStandStill2");
        leGetStandStill2->setGeometry(QRect(140, 80, 101, 41));
        btnSetAngle2 = new QPushButton(tab_4);
        btnSetAngle2->setObjectName("btnSetAngle2");
        btnSetAngle2->setGeometry(QRect(10, 260, 121, 51));
        frameFallDetection_5 = new QFrame(tab_4);
        frameFallDetection_5->setObjectName("frameFallDetection_5");
        frameFallDetection_5->setGeometry(QRect(10, 40, 121, 41));
        frameFallDetection_5->setFrameShape(QFrame::Shape::StyledPanel);
        frameFallDetection_5->setFrameShadow(QFrame::Shadow::Raised);
        cbFallDetection2 = new QCheckBox(frameFallDetection_5);
        cbFallDetection2->setObjectName("cbFallDetection2");
        cbFallDetection2->setGeometry(QRect(10, 10, 111, 20));
        frameFallDetection_6 = new QFrame(frameFallDetection_5);
        frameFallDetection_6->setObjectName("frameFallDetection_6");
        frameFallDetection_6->setGeometry(QRect(70, 40, 121, 41));
        frameFallDetection_6->setFrameShape(QFrame::Shape::StyledPanel);
        frameFallDetection_6->setFrameShadow(QFrame::Shadow::Raised);
        frame_11 = new QFrame(tab_4);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(10, 80, 120, 41));
        frame_11->setFrameShape(QFrame::Shape::StyledPanel);
        frame_11->setFrameShadow(QFrame::Shadow::Raised);
        cbStandStill2 = new QCheckBox(frame_11);
        cbStandStill2->setObjectName("cbStandStill2");
        cbStandStill2->setGeometry(QRect(10, 10, 101, 20));
        frame_12 = new QFrame(frame_11);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(60, 40, 120, 41));
        frame_12->setFrameShape(QFrame::Shape::StyledPanel);
        frame_12->setFrameShadow(QFrame::Shadow::Raised);
        cbStandStill_6 = new QCheckBox(frame_12);
        cbStandStill_6->setObjectName("cbStandStill_6");
        cbStandStill_6->setGeometry(QRect(10, 10, 101, 20));
        leSetFallDuration2 = new QLineEdit(tab_4);
        leSetFallDuration2->setObjectName("leSetFallDuration2");
        leSetFallDuration2->setGeometry(QRect(140, 210, 101, 41));
        leAngleZ2 = new QLineEdit(tab_4);
        leAngleZ2->setObjectName("leAngleZ2");
        leAngleZ2->setGeometry(QRect(220, 260, 31, 41));
        tw->addTab(tab_4, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName("tab_3");
        label_3 = new QLabel(tab_3);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(20, 10, 81, 16));
        leMotion = new QLineEdit(tab_3);
        leMotion->setObjectName("leMotion");
        leMotion->setGeometry(QRect(150, 0, 101, 31));
        label_2 = new QLabel(tab_3);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 50, 81, 16));
        leStandStill = new QLineEdit(tab_3);
        leStandStill->setObjectName("leStandStill");
        leStandStill->setGeometry(QRect(150, 30, 101, 41));
        leStandStill->setStyleSheet(QString::fromUtf8("background-color: rgb(169, 144, 255);"));
        label = new QLabel(tab_3);
        label->setObjectName("label");
        label->setGeometry(QRect(20, 90, 81, 16));
        btnTestFall = new QPushButton(tab_3);
        btnTestFall->setObjectName("btnTestFall");
        btnTestFall->setGeometry(QRect(100, 80, 41, 41));
        leFallState = new QLabel(tab_3);
        leFallState->setObjectName("leFallState");
        leFallState->setGeometry(QRect(150, 70, 101, 51));
        leFallState->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 208);"));
        leFallState->setFrameShape(QFrame::Shape::Box);
        label_4 = new QLabel(tab_3);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 130, 51, 16));
        label_5 = new QLabel(tab_3);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(20, 170, 81, 16));
        leFallPosX = new QLineEdit(tab_3);
        leFallPosX->setObjectName("leFallPosX");
        leFallPosX->setGeometry(QRect(150, 130, 101, 31));
        leFallPosY = new QLineEdit(tab_3);
        leFallPosY->setObjectName("leFallPosY");
        leFallPosY->setGeometry(QRect(150, 160, 101, 31));
        label_7 = new QLabel(tab_3);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(20, 200, 81, 16));
        leVelocity = new QLineEdit(tab_3);
        leVelocity->setObjectName("leVelocity");
        leVelocity->setGeometry(QRect(150, 190, 101, 31));
        label_6 = new QLabel(tab_3);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(20, 230, 81, 16));
        leTraceNumber = new QLineEdit(tab_3);
        leTraceNumber->setObjectName("leTraceNumber");
        leTraceNumber->setGeometry(QRect(150, 220, 101, 31));
        cbSocket = new QCheckBox(tab_3);
        cbSocket->setObjectName("cbSocket");
        cbSocket->setGeometry(QRect(20, 250, 86, 20));
        logEdit = new QPlainTextEdit(tab_3);
        logEdit->setObjectName("logEdit");
        logEdit->setGeometry(QRect(10, 280, 341, 111));
        tw->addTab(tab_3, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName("tab_6");
        label_15 = new QLabel(tab_6);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(20, 240, 81, 16));
        label_16 = new QLabel(tab_6);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(20, 210, 81, 16));
        btnTestFall2 = new QPushButton(tab_6);
        btnTestFall2->setObjectName("btnTestFall2");
        btnTestFall2->setGeometry(QRect(100, 90, 41, 41));
        leTraceNumber2 = new QLineEdit(tab_6);
        leTraceNumber2->setObjectName("leTraceNumber2");
        leTraceNumber2->setGeometry(QRect(150, 230, 101, 31));
        logEdit2 = new QPlainTextEdit(tab_6);
        logEdit2->setObjectName("logEdit2");
        logEdit2->setGeometry(QRect(10, 290, 341, 111));
        leFallPosY2 = new QLineEdit(tab_6);
        leFallPosY2->setObjectName("leFallPosY2");
        leFallPosY2->setGeometry(QRect(150, 170, 101, 31));
        label_17 = new QLabel(tab_6);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(20, 100, 81, 16));
        leVelocity2 = new QLineEdit(tab_6);
        leVelocity2->setObjectName("leVelocity2");
        leVelocity2->setGeometry(QRect(150, 200, 101, 31));
        leFallState2 = new QLabel(tab_6);
        leFallState2->setObjectName("leFallState2");
        leFallState2->setGeometry(QRect(150, 80, 101, 51));
        leFallState2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 208);"));
        leFallState2->setFrameShape(QFrame::Shape::Box);
        label_18 = new QLabel(tab_6);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(20, 140, 51, 16));
        label_19 = new QLabel(tab_6);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(20, 60, 81, 16));
        label_20 = new QLabel(tab_6);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(20, 180, 81, 16));
        leStandStill2 = new QLineEdit(tab_6);
        leStandStill2->setObjectName("leStandStill2");
        leStandStill2->setGeometry(QRect(150, 40, 101, 41));
        leStandStill2->setStyleSheet(QString::fromUtf8("background-color: rgb(169, 144, 255);"));
        leFallPosX2 = new QLineEdit(tab_6);
        leFallPosX2->setObjectName("leFallPosX2");
        leFallPosX2->setGeometry(QRect(150, 140, 101, 31));
        leMotion2 = new QLineEdit(tab_6);
        leMotion2->setObjectName("leMotion2");
        leMotion2->setGeometry(QRect(150, 10, 101, 31));
        cbSocket2 = new QCheckBox(tab_6);
        cbSocket2->setObjectName("cbSocket2");
        cbSocket2->setGeometry(QRect(20, 260, 86, 20));
        label_21 = new QLabel(tab_6);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(20, 20, 81, 16));
        tw->addTab(tab_6, QString());
        plotRadar = new QCustomPlot(centralWidget);
        plotRadar->setObjectName("plotRadar");
        plotRadar->setGeometry(QRect(370, 300, 250, 150));
        sizePolicy.setHeightForWidth(plotRadar->sizePolicy().hasHeightForWidth());
        plotRadar->setSizePolicy(sizePolicy);
        plottsVelocity = new QCustomPlot(centralWidget);
        plottsVelocity->setObjectName("plottsVelocity");
        plottsVelocity->setGeometry(QRect(370, 160, 250, 141));
        sizePolicy.setHeightForWidth(plottsVelocity->sizePolicy().hasHeightForWidth());
        plottsVelocity->setSizePolicy(sizePolicy);
        plottsgram2 = new QCustomPlot(centralWidget);
        plottsgram2->setObjectName("plottsgram2");
        plottsgram2->setGeometry(QRect(620, 10, 250, 150));
        sizePolicy.setHeightForWidth(plottsgram2->sizePolicy().hasHeightForWidth());
        plottsgram2->setSizePolicy(sizePolicy);
        plottsVelocity2 = new QCustomPlot(centralWidget);
        plottsVelocity2->setObjectName("plottsVelocity2");
        plottsVelocity2->setGeometry(QRect(620, 160, 250, 141));
        sizePolicy.setHeightForWidth(plottsVelocity2->sizePolicy().hasHeightForWidth());
        plottsVelocity2->setSizePolicy(sizePolicy);
        plotRadar2 = new QCustomPlot(centralWidget);
        plotRadar2->setObjectName("plotRadar2");
        plotRadar2->setGeometry(QRect(620, 300, 250, 150));
        sizePolicy.setHeightForWidth(plotRadar2->sizePolicy().hasHeightForWidth());
        plotRadar2->setSizePolicy(sizePolicy);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName("menuBar");
        menuBar->setGeometry(QRect(0, 0, 889, 30));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName("mainToolBar");
        MainWindow->addToolBar(Qt::ToolBarArea::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName("statusBar");
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tw->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        btnGetFallDuration->setText(QCoreApplication::translate("MainWindow", "Get Fall Duration", nullptr));
        btnGetHeightInst->setText(QCoreApplication::translate("MainWindow", "Get Height Inst", nullptr));
        btnGetAngleInst->setText(QCoreApplication::translate("MainWindow", "Get Angle Inst", nullptr));
        btnCmdInitCompleteCek->setText(QCoreApplication::translate("MainWindow", "Init Complete", nullptr));
        btnGetFirmwareVersion->setText(QCoreApplication::translate("MainWindow", "Firmware Ver", nullptr));
        btnHWModel->setText(QCoreApplication::translate("MainWindow", "H/W Model", nullptr));
        btnGetProductModel->setText(QCoreApplication::translate("MainWindow", "Product Model", nullptr));
        btnGetProductID->setText(QCoreApplication::translate("MainWindow", "Get Product ID", nullptr));
        tw->setTabText(tw->indexOf(tab), QCoreApplication::translate("MainWindow", "Specs1", nullptr));
        btnGetProductModel2->setText(QCoreApplication::translate("MainWindow", "Product Model", nullptr));
        btnCmdInitCompleteCek2->setText(QCoreApplication::translate("MainWindow", "Init Complete", nullptr));
        btnGetProductID2->setText(QCoreApplication::translate("MainWindow", "Get Product ID", nullptr));
        btnGetFallDuration2->setText(QCoreApplication::translate("MainWindow", "Get Fall Duration", nullptr));
        btnHWModel2->setText(QCoreApplication::translate("MainWindow", "H/W Model", nullptr));
        btnGetAngleInst2->setText(QCoreApplication::translate("MainWindow", "Get Angle Inst", nullptr));
        btnGetFirmwareVersion2->setText(QCoreApplication::translate("MainWindow", "Firmware Ver", nullptr));
        btnGetHeightInst2->setText(QCoreApplication::translate("MainWindow", "Get Height Inst", nullptr));
        tw->setTabText(tw->indexOf(tab_5), QCoreApplication::translate("MainWindow", "Specs2", nullptr));
        cbPresence->setText(QCoreApplication::translate("MainWindow", "Presence", nullptr));
        cbFallDetection->setText(QCoreApplication::translate("MainWindow", "Fall Detection", nullptr));
        cbStandStill->setText(QCoreApplication::translate("MainWindow", "StandStill", nullptr));
        cbStandStill_2->setText(QCoreApplication::translate("MainWindow", "StandStill", nullptr));
        btnSetHeight->setText(QCoreApplication::translate("MainWindow", "Set Height Inst", nullptr));
        leSetHeight->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        leSetFallDuration->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        btnSetFallDuration->setText(QCoreApplication::translate("MainWindow", "Set Fall Duration", nullptr));
        btnSetAngle->setText(QCoreApplication::translate("MainWindow", "Set Angle", nullptr));
        leAngleX->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        leAngleY->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        leAngleZ->setText(QCoreApplication::translate("MainWindow", "30", nullptr));
        cbTraceTracking->setText(QCoreApplication::translate("MainWindow", "Trace Tracking", nullptr));
        btnOpenSerialPort->setText(QCoreApplication::translate("MainWindow", "Open", nullptr));
        btnLoad->setText(QCoreApplication::translate("MainWindow", "LOAD", nullptr));
        tw->setTabText(tw->indexOf(tab_2), QCoreApplication::translate("MainWindow", "SetR1", nullptr));
        cbTraceTracking2->setText(QCoreApplication::translate("MainWindow", "Trace Tracking", nullptr));
        btnSetHeight2->setText(QCoreApplication::translate("MainWindow", "Set Height Inst", nullptr));
        leAngleX2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        leAngleY2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        btnLoad2->setText(QCoreApplication::translate("MainWindow", "LOAD", nullptr));
        leSetHeight2->setText(QCoreApplication::translate("MainWindow", "100", nullptr));
        btnSetFallDuration2->setText(QCoreApplication::translate("MainWindow", "Set Fall Duration", nullptr));
        btnOpenSerialPort2->setText(QCoreApplication::translate("MainWindow", "Open", nullptr));
        cbPresence2->setText(QCoreApplication::translate("MainWindow", "Presence", nullptr));
        btnSetAngle2->setText(QCoreApplication::translate("MainWindow", "Set Angle", nullptr));
        cbFallDetection2->setText(QCoreApplication::translate("MainWindow", "Fall Detection", nullptr));
        cbStandStill2->setText(QCoreApplication::translate("MainWindow", "StandStill", nullptr));
        cbStandStill_6->setText(QCoreApplication::translate("MainWindow", "StandStill", nullptr));
        leSetFallDuration2->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        leAngleZ2->setText(QCoreApplication::translate("MainWindow", "30", nullptr));
        tw->setTabText(tw->indexOf(tab_4), QCoreApplication::translate("MainWindow", "SetR2", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Motion", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "STAND STILL", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "FALL STATE", nullptr));
        btnTestFall->setText(QCoreApplication::translate("MainWindow", "FALL", nullptr));
        leFallState->setText(QCoreApplication::translate("MainWindow", "NOT FALL", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Speed", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Trace Number", nullptr));
        cbSocket->setText(QCoreApplication::translate("MainWindow", "Socket", nullptr));
        tw->setTabText(tw->indexOf(tab_3), QCoreApplication::translate("MainWindow", "RunView1", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Trace Number", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Speed", nullptr));
        btnTestFall2->setText(QCoreApplication::translate("MainWindow", "FALL", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "FALL STATE", nullptr));
        leFallState2->setText(QCoreApplication::translate("MainWindow", "NOT FALL", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "STAND STILL", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        cbSocket2->setText(QCoreApplication::translate("MainWindow", "Socket", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Motion", nullptr));
        tw->setTabText(tw->indexOf(tab_6), QCoreApplication::translate("MainWindow", "RunView2", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
